OnlineTicketWeb/Controllers/EventController.cs
using AutoMapper;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using OnlineTicketData.Db;
using OnlineTicketData.Models;
using OnlineTicketData.Models.DTO;
using OnlineTicketData.StaticData;
using OnlineTicketWeb.Services.IServices;
using System;
using System.Collections.Generic;
using System.Reflection;

namespace OnlineTicketWeb.Controllers
{
    [Authorize(Roles =SD.Role_Admin)]
    public class EventController : Controller
    {
        private readonly IEventService _eventService;
        private readonly IMapper _mapper;
        
        public EventController(IEventService eventService, IMapper mapper)
        {
            _eventService = eventService;
            _mapper = mapper;
            
        }

        public async Task<IActionResult> IndexEvent()
        {
            List<Event> list = new();

            var response = await _eventService.GetAllAsync<APIResponse>();
         
            if (response != null)
            {
              
                list = JsonConvert.DeserializeObject<List<Event>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

         // [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateEvent()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEvent(EventDTO model)
        {
            if (ModelState.IsValid)
            {

                var response = await _eventService.CreateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Event created successfully";
                    return RedirectToAction(nameof(IndexEvent));
                }
            }
              TempData["error"] = "Error encountered.";
            return View(model);

        }

        //  [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateEvent(int eventId)
        {
            var response = await _eventService.GetAsync<APIResponse>(eventId);
            if (response != null && response.IsSuccess)
            {

                Event model = JsonConvert.DeserializeObject<Event>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }



         // [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateEvent(Event model)
        {
            if (ModelState.IsValid)
            {
               
                var response = await _eventService.UpdateAsync<APIResponse>(model);
               
                if (response != null && response.IsSuccess)
                {
                   TempData["success"] = "Event updated successfully";
                    return RedirectToAction(nameof(IndexEvent));
                }
            }
              TempData["error"] = "Error encountered.";
            return View(model);
        }


        ////  // [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteEvent(int eventId)
        {
            var response = await _eventService.GetAsync<APIResponse>(eventId);
            if (response != null && response.IsSuccess)
            {
                Event model = JsonConvert.DeserializeObject<Event>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }



        //// //  [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteEvent(Event model)
        {

            var response = await _eventService.DeleteAsync<APIResponse>(model.EventId);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Event deleted successfully";
                return RedirectToAction(nameof(IndexEvent));
            }
            TempData["error"] = "Error encountered.";
            return View(model);
        }






      

        
    }
}

OnlineTicketWeb/ViewComponents/CountdownViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineTicketData.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using OnlineTicketData.Models;
using OnlineTicketData.Models.ViewModels;
using OnlineTicketWeb.Services.IServices;
using Newtonsoft.Json;
using OnlineTicketData.Repository.IRepository;

namespace OnlineTicketWeb.ViewComponents
{
   
    public class CountdownViewComponent : ViewComponent
    {
        private readonly IEventRepository _eventService;

        public CountdownViewComponent(IEventRepository eventService)
        {
            _eventService = eventService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {


            List<Event> list = await _eventService.GetAllAsync();
           
          
            
            var today = DateTime.Today;

            var firstEvent = list
                .Where(e => e.EventDate == today)
                .OrderBy(e => e.EventDate)
                .FirstOrDefault();

            if (firstEvent != null)
            {
                var countdownTime = firstEvent.EventDate - DateTime.Now;

                var model = new CountdownViewModel
                {
                    CountdownTime = countdownTime
                };

                return View(model);
            }

            // No event found for today
            return Content("No events today.");
        }
    }
}

OnlineTicketWeb/Views/Event/CreateEvent.cshtml
@model OnlineTicketData.Models.DTO.EventDTO

<form asp-action="CreateEvent">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Event</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="EventName" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="EventDescription" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="EventDescription" class="form-control" rows="5"></textarea>
                <span asp-validation-for="EventDescription" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="EventDate" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input type="date" asp-for="EventDate" class="form-control" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="EventLocation" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="EventLocation" class="form-control" />
                <span asp-validation-for="EventLocation" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="AvailableSeats" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="AvailableSeats" class="form-control" />
                <span asp-validation-for="AvailableSeats" class="text-danger"></span>
            </div>

           
            <div class="col-5 offset-2">
                <a asp-action="IndexEvent" asp-controller="Event" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

OnlineTicketWeb/Views/Event/DeleteEvent.cshtml
@model OnlineTicketData.Models.Event

<form asp-action="DeleteEvent">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete Event</h1>
        <hr />

        <input hidden asp-for="EventId" />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="EventName" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="EventName" class="form-control" />
              
            </div>

            <div class="col-2">
                <label asp-for="EventDescription" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="EventDescription" class="form-control" rows="5"></textarea>
              
            </div>



            <div class="col-2">
                <label asp-for="EventDate" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input type="date" asp-for="EventDate" class="form-control" />
               
            </div>

            <div class="col-2">
                <label asp-for="EventLocation" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="EventLocation" class="form-control" />
             
            </div>

            <div class="col-2">
                <label asp-for="AvailableSeats" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="AvailableSeats" class="form-control" />
               
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexEvent" asp-controller="Event" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

OnlineTicketWeb/Views/Event/IndexEvent.cshtml
@model IEnumerable<Event>
@using OnlineTicketData.Models
@using System.ComponentModel;


@if (TempData["success"] != null)
{
    <h2>@TempData["success"]</h2>
}
<br />


<h2>Event Lists</h2>
<div class="col text-end pt-1">
    <a asp-controller="Event" asp-action="CreateEvent" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i>Create Event</a>
</div>

@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    EventName
                </th>
                <th>
                    EventDescription
                </th>
                <th>
                    EventDate
                </th>
                <th>
                    EventLocation
                </th>
                <th>
                    AvailableSeats
                </th>
               @* <th>
                    IsApproved
                </th>*@
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var result in Model)
            {

                Html.RenderPartial("_EventPartial", result);

                <tr>
                    <td>
                     
                        <a asp-action="Edit" asp-route-id="@result.EventId">Edit</a>
                        <a asp-action="Delete" asp-route-id="@result.EventId">Delete</a>
                    </td>
                </tr>



           
            }
        </tbody>
    </table>
   
    @*  @await Component.InvokeAsync("Countdown")*@
}
else
{
    <p>No Events available.</p>
}

OnlineTicketWeb/Views/Event/UpdateEvent.cshtml
@model OnlineTicketData.Models.Event

<form asp-action="UpdateEvent">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update Event</h1>
        <hr />

        <input hidden asp-for="EventId" />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="EventName" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="EventDescription" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="EventDescription" class="form-control" rows="5"></textarea>
                <span asp-validation-for="EventDescription" class="text-danger"></span>
            </div>

           
           
            <div class="col-2">
                <label asp-for="EventDate" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input type="date" asp-for="EventDate" class="form-control" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="EventLocation" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="EventLocation" class="form-control" />
                <span asp-validation-for="EventLocation" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="AvailableSeats" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="AvailableSeats" class="form-control" />
                <span asp-validation-for="AvailableSeats" class="text-danger"></span>
            </div>

          
            <div class="col-5 offset-2">
                <a asp-action="IndexEvent" asp-controller="Event" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}