OnlineTicketWeb/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineTicketData.StaticData;
using OnlineTicketWeb.Services.IServices;
using System.Data;

namespace OnlineTicketWeb.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class AdminController:Controller
    {
        private readonly IAdminService _adminService;

        public AdminController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        public async Task<IActionResult> Index()
        {
            var events = await _adminService.GetEventsAsync();
            return View(events);
        }

        public async Task<IActionResult> Approve(int id)
        {
            var eventToApprove = _adminService.ApprovedEvent(id);
           

            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> Reject(int id)
        {
           
                await _adminService.RejectEvent(id);
                return RedirectToAction("Index");
           
           
        }

        //public async Task<IActionResult> PendingApproval()
        //{
        //    var pendingEvents =await _eventService.GetAsync(e => !e.IsApproved).ToList();
        //    return View(pendingEvents);
        //}


    }
}
    

OnlineTicketWeb/Controllers/EventController.cs
using AutoMapper;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using OnlineTicketData.Db;
using OnlineTicketData.Models;
using OnlineTicketData.Models.DTO;
using OnlineTicketData.StaticData;
using OnlineTicketWeb.Services.IServices;
using System;
using System.Collections.Generic;
using System.Reflection;

namespace OnlineTicketWeb.Controllers
{
    [Authorize(Roles =SD.Role_Admin)]
    public class EventController : Controller
    {
        private readonly IEventService _eventService;
        private readonly IMapper _mapper;
        
        public EventController(IEventService eventService, IMapper mapper)
        {
            _eventService = eventService;
            _mapper = mapper;
            
        }

        public async Task<IActionResult> IndexEvent()
        {
            List<Event> list = new();

            var response = await _eventService.GetAllAsync<APIResponse>();
         
            if (response != null)
            {
              
                list = JsonConvert.DeserializeObject<List<Event>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

         // [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateEvent()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEvent(EventDTO model)
        {
            if (ModelState.IsValid)
            {

                var response = await _eventService.CreateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Event created successfully";
                    return RedirectToAction(nameof(IndexEvent));
                }
            }
              TempData["error"] = "Error encountered.";
            return View(model);

        }

        //  [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateEvent(int eventId)
        {
            var response = await _eventService.GetAsync<APIResponse>(eventId);
            if (response != null && response.IsSuccess)
            {

                Event model = JsonConvert.DeserializeObject<Event>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }



         // [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateEvent(Event model)
        {
            if (ModelState.IsValid)
            {
               
                var response = await _eventService.UpdateAsync<APIResponse>(model);
               
                if (response != null && response.IsSuccess)
                {
                   TempData["success"] = "Event updated successfully";
                    return RedirectToAction(nameof(IndexEvent));
                }
            }
              TempData["error"] = "Error encountered.";
            return View(model);
        }


        ////  // [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteEvent(int eventId)
        {
            var response = await _eventService.GetAsync<APIResponse>(eventId);
            if (response != null && response.IsSuccess)
            {
                Event model = JsonConvert.DeserializeObject<Event>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }



        //// //  [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteEvent(Event model)
        {

            var response = await _eventService.DeleteAsync<APIResponse>(model.EventId);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Event deleted successfully";
                return RedirectToAction(nameof(IndexEvent));
            }
            TempData["error"] = "Error encountered.";
            return View(model);
        }






      

        
    }
}

OnlineTicketWeb/Controllers/TicketBookingController.cs
using AutoMapper;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using OnlineTicketData.Models;
using OnlineTicketData.Models.DTO;
using OnlineTicketData.StaticData;
using OnlineTicketWeb.Services;
using OnlineTicketWeb.Services.IServices;
using System.Collections.Generic;
using System.Data;
using System.Net.Sockets;

namespace OnlineTicketWeb.Controllers
{
    [Authorize]
    public class TicketBookingController : Controller
    {
        private readonly ITicketBookingService _ticketBookingService;
        private readonly IEventService _eventService;
        private readonly IMapper _mapper;
        public TicketBookingController(ITicketBookingService ticketBookingService, IMapper mapper, IEventService eventService)
        {
            _ticketBookingService = ticketBookingService;
            _mapper = mapper;
            _eventService = eventService;
        }

        public async Task<IActionResult> IndexTicketBooking()
        {
            List<TicketBooking> list = new();

            var response = await _ticketBookingService.GetAllAsync<APIResponse>();
            // var events=await _eventService.GetAllAsync<APIResponse>();
            // ViewBag.events = events;


            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<TicketBooking>>(Convert.ToString(response.Result));
            }
            return View(list);
        }



        
        public async Task<IActionResult> BookTicket()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BookTicket(TicketBookingDTO ticket)
        {
            var response = await _ticketBookingService.CreateAsync<APIResponse>(ticket);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Ticked Booked successfully";
                return RedirectToAction(nameof(IndexTicketBooking));
            }
        
             TempData["error"] = "Error encountered.";
           
            return View(ticket);
        }

     
        public async Task<IActionResult> Delete(int id)
        {

            var response = await _ticketBookingService.GetAsync<APIResponse>(id);
            if (response != null && response.IsSuccess)
            {
                Event model = JsonConvert.DeserializeObject<Event>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteEvent(TicketBooking model)
        {

            var response = await _ticketBookingService.DeleteAsync<APIResponse>(model.TicketId);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Ticket deleted successfully";
                return RedirectToAction(nameof(IndexTicketBooking));
            }
            TempData["error"] = "Error encountered.";
            return View(model);
        }


        public async Task<IActionResult> ViewBookedTickets()
        {
            List<TicketBooking> list = new();

            var response = await _ticketBookingService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<TicketBooking>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
    }

}

OnlineTicketWeb/Views/Shared/_EventPartial.cshtml
@model Event

<tr>
    <td>@Model.EventName</td>
    <td>@Model.EventDescription</td>
    <td>@Model.EventDate</td>
    <td>@Model.EventLocation</td>
    <td>@Model.AvailableSeats</td>
  @*  <td>@Model.IsApproved</td>*@
</tr>

OnlineTicketWeb/Views/Shared/_Layout.cshtml
@using OnlineTicketData.StaticData

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineTicketWeb</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineTicketWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark  box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineTicketWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                       

                        @if (User.IsInRole(SD.Role_Admin))
                        {
                          
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="IndexEvent"> Event List</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">View Pending Events</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TicketBooking" asp-action="IndexTicketBooking"> All Events</a>
                            </li>

                          
                            <li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="TicketBooking" asp-action="ViewBookedTickets">View Booked Tickets</a>
                        </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div >
            &copy; 2023 - OnlineTicketWeb 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>